### PR TITLE
add jordan wigner for _plane_wave_hamiltonian

### PR DESCRIPTION
**Pull request by Spaceenter**

### CODE REVIEW

**Comment by Spaceenter** [comment]
@babbush 
Formula (D6) still seems problematic, so this implementation is using formula (D5) directly.

**Comment by babbush** [comment]
What part of D6 is problematic? Is it just the identity term that is not looking correct?

**Comment by Spaceenter** [comment]
Not only the identity term, but also (potentially) the Z term.

What I found is that _jellium_test fails if I remove either of the following two lines (according to the formula, those two lines should be removed):


https://github.com/ProjectQ-Framework/FermiLib/blob/develop/src/fermilib/utils/_jellium.py#L378
https://github.com/ProjectQ-Framework/FermiLib/blob/develop/src/fermilib/utils/_jellium.py#L392

However, the good thing is, even using (D5), the performance shouldn't in influenced that much, as most of the computations are for XZX/YZY, which is orders of magnitude more complex than Z term and I term.
@babbush

**Comment by babbush** [comment]
Thanks Wei. This is super helpful.

**Pull request merged**
