### PR TITLE
Made sure eigenspectra is always sorted.

### PR DESCRIPTION
**Pull request by babbush**

### CODE REVIEW

**Comment by babbush** [comment]
No I don't think so because get_gap calls the Lancoz algorithm whereas eigenspectra calls a dense diagonalization. So I think we're fine.

**Comment by idk3** [comment]
Good point, I didn't notice that one uses numpy.linalg while the other uses
scipy.linalg. Should be all fine.

**Comment by Spaceenter** [comment]
It'd be nice to add a test in _plane_wave_hamiltonian_test.py to test when grid_length = 2^n (could be a follow up pull request when the spin issue is sorted out).

**Comment by jarrodmcc** [comment]
We should probably change all instances to sp.linalg.eigh just for consistency, so if one changes within the library, we can detect and handle the changes more easily.

However, to the point of this commit, doing it this way will cause an error in general.  The reason eig doesn't return ordered values is because given a non-symmetric matrix, it can return complex eigenvalues, which are not well ordered.  When this does happen (even if only to numerical roundoff), using a sort routine will raise a TypeError as a result.  

Testing it in my terminal, the exact error will be "TypeError: no ordering relation is defined for complex numbers".

**Comment by idk3** [comment]
@jarrodmcc this is true for sorting a list, but not if you use numpy's `sort` or `sort_complex` (which both seem to give the same output).

**Comment by idk3** [comment]
But I see your point in general, I guess - not sure how to handle ideally...

**Comment by jarrodmcc** [comment]
That seems fine in that case then, not sure if it's worth mentioning in the comments of the function that the order returned for complex numbers is defined by numpy and not any canonical mathematical ordering.

**Pull request merged**
