### PR TITLE
Refactoring operator utils test

### PR DESCRIPTION
**Pull request by idk3**

### CODE REVIEW

**Review by babbush — DISMISSED** [review]

**Comment by idk3** [comment]
@babbush @damiansteiger - ?

**Comment by babbush** [comment]
What? Your PR is not passing tests.

**Comment by idk3** [comment]
"The command "pip$PY install --only-binary=numpy,scipy numpy scipy" failed and exited with 2 during ."

Doesn't look like an error on my end, and it only failed for Python 3.5 - not sure if I should push again or if there's something else

**Comment by idk3** [comment]
@babbush @damiansteiger it looks like travis is temporarily dead, my other PR got ImportErrors on every module :P I'll try resubmitting both in an hour.

**Review by babbush — APPROVED** [review]

**Pull request merged**
