### PR TITLE
Extract common helper from fourier_transform / inverse_fourier_transform

### PR DESCRIPTION
**Pull request by Strilanc**
They're large almost identical methods, so I merged them into a helper then called it with slightly different arguments.

I did it in two stages:

1. Making the same except for assignments at the top. I used rename refactorings to fix differences in variable names. I fixed differences in logic by depending on the assignment values instead of hard-coded functions. I confirmed the function tails were exactly identical at this point by pasting one over the other and confirming no diff.

2. Moving the common bodies into a method then calling it.

### CODE REVIEW

**Comment by Strilanc** [comment]
This is actually a subset of another PR that you approved...?

There were two big complicated methods, but they were almost identical. Any bugfix you make to one would have to be repeated on the other. Any feature you added to one would also be added to the other. There's no reason to do all that work, and all that reading, twice. This pulls out their common structure so that changes only have to be made once.

**Comment by babbush** [comment]
Ok, just change the names as I mentioned and I will approve.

**Comment by Strilanc** [comment]
Are the name changes appropriate? When doing the inverse transform they would be the opposite of what they should be. I'm fine with using good names instead of generic ones, but we should avoid directly misleading names.

**Comment by Strilanc** [comment]
Please suggest alternative names so that this can get pushed; it will have merge conflicts with some of the grid changes.

**Pull request merged**
