### PR TITLE
Remove orbital overlaps from molecular data

### PR DESCRIPTION
**Pull request by jarrodmcc**
This removes the orbital overlaps from the molecular data class.  This is because we made a design decision to always work in orthonormal bases, so this is always just the trivial identity matrix.  That is, it is up to the user or plugin to do this transformation before handing it off to FermiLib.  If we decide to add in functionality for non-orthogonal basis sets, this can be added back later with the appropriate bells and whistles.  Additionally a bug was causing previous versions to spit out the one-body integrals by mistake, so it is better in the short term to remove it as well.

### CODE REVIEW

**Review by babbush — DISMISSED** [review]
:+1:

**Comment by babbush** [comment]
This is five lines of code which I spoke to Jarrod about in person as he was writing. Why did you block?

**Comment by damiansteiger** [comment]
@jarrodmcc: Did you sign your new CLA?

**Comment by babbush** [comment]
Oh. Please send a new one to him right away and we will sign immediately.

**Review by damiansteiger — DISMISSED** [review]
Thanks for the new CLA. You are good to go  👍

**Review by babbush — APPROVED** [review]
:+1:

**Pull request merged**
