### PR TITLE
Dual basis expectation with plane-wave state

### PR DESCRIPTION
**Pull request by idk3**

### CODE REVIEW

**Comment by idk3** [comment]
@babbush this should fail (hopefully only) due to decreased test coverage from the unittest.skip - can you load it to yours and run it with the skip commented out?

**Comment by babbush** [comment]
Why? I'm not entirely sure what you are asking. Pull requests are to contribute code to the library. You should only contribute code that passes all the tests. Do you have something else in mind?

**Comment by idk3** [comment]
@damiansteiger do you know what might be causing this? My builds are all getting `The command "pip$PY install -r requirements.txt" failed and exited with 1 during .` in output.

**Comment by damiansteiger** [comment]
It is due to a new pybind version (https://github.com/ProjectQ-Framework/ProjectQ/issues/144)

Either wait for the fix or add a requirement to install the old pybind version before it installs ProjectQ.

**Comment by damiansteiger** [comment]
The issue of pybind11 and ProjectQ is fixed in the new version 0.3.3

**Comment by idk3** [comment]
Thanks!!

**Review by babbush — APPROVED** [review]
LGTM

**Pull request merged**
