### PR TITLE
Use Grid for plane_wave_u_operator, dual_basis_u_operator, plane_wave_hamiltonian

### PR DESCRIPTION
**Pull request by Strilanc**
Comes after https://github.com/ProjectQ-Framework/FermiLib/pull/31

### CODE REVIEW

**Comment by babbush** [comment]
merging seems to have broken some tests

**Comment by Strilanc** [comment]
Don't merge this yet (that's why [Blocked] is in the title). It needs to be rebased to expunge the non-CLA commit.

**Comment by Strilanc** [comment]
Fixed the merge conflict and rebased.

**Comment by babbush** [comment]
@damiansteiger It seems that you are the only one who has permission to review this since @Strilanc requested you.

**Comment by damiansteiger** [comment]
>damiansteiger self-requested a review 2 days ago

I add myself as a reviewer for certain pull requests. You should still be able to do a code review and approve it if you like. However, you have to wait until I either approve it as well or remove myself as a reviewer. 

In this case I have added myself as a reviewer because until the 
> Fixed the merge conflict and rebased.
there was still the old commit in here which had a missing CLA. Therefore, I blocked merging this in order to make sure that this pull request was properly rebased which Strilanc did 👍  As this was done, I remove my review request, so @babbush you can go ahead.
In other cases, I add myself as a reviewer if it concerns key data structures such a FermionOperator...

**Pull request merged**
