### PR TITLE
Opt

### PR DESCRIPTION
**Pull request by Spaceenter**
Optimize a few functions in _sparse_tools.py.

For 2D (4x4), this improves the running time from 86s to 16s on my mac. For 3D, the improvement should be much more.

### CODE REVIEW

**Comment by Spaceenter** [comment]
@babbush @idk3

**Comment by Spaceenter** [comment]
Hmm.. It seems to fail for python3 - will try to fix.

**Comment by babbush** [comment]
Looks like a couple more tests may also be needed.

**Comment by Spaceenter** [comment]
Fixed, and tests are OK now - please take a look again. @babbush @idk3

**Review by babbush — APPROVED** [review]

**Comment by babbush** [comment]
Coveralls appears to be down.

**Comment by damiansteiger** [comment]
Why did you close this PR? just re-run travis and coveralls might eventually work

**Pull request merged**
