### PR TITLE
Handled IOError in MolecularData.get_from_file() function

### PR DESCRIPTION
**Pull request by hsim13372**
I tried to set up an instance of MolecularData that was a "new" molecule (ie molecule that didn't exist in the default data directory in FermiLib) and ran into an IOError because the function get_from_file() in MolecularData didn't handle it/assumed this MolecularData instance has been saved into a HDF5 file.

### CODE REVIEW

**Review by babbush — APPROVED** [review]
Looks like some tests are failing.

**Comment by idk3** [comment]
The test that failed isn't linked to Hannah's PR - is it possible there's some randomness in ProjectQ? Increasing the Trotter number for the failed test will likely fix it, but I'm not sure why it failed to begin with

**Comment by babbush** [comment]
This is new. @damiansteiger, @thomashaener any idea what's happening here?

**Comment by damiansteiger** [comment]
I don't know and currently I don't have FermiLib installed to debug.

Given that ProjectQ did not change in the last 22 days, my bet is an error in FermiLib as otherwise it would/could have appeared earlier. Might be because of randomness. If you like you can seed the random number generator of ProjectQ (see [docs](http://projectq.readthedocs.io/en/latest/projectq.backends.html?highlight=simulator#projectq.backends.Simulator)) but the test in FermiLib is clearly random:
```
for i in range(len(initial_state)):
            initial_state[i] = (random.random() *
                                numpy.exp(1j * 2 * numpy.pi * random.random()))
```
So maybe that is the problem...

**Comment by idk3** [comment]
Good point, is the best option to set a numpy seed for those? Could
alternatively raise the trotter number. (Don't want to have to set the full
vector, but can see how it might look hacky otherwise)

**Comment by babbush** [comment]
You should absolutely hard seed any random tests!

**Comment by damiansteiger** [comment]
For a start, I would seed the `random.random()`. No need to seed the ProjectQ simulator as you don't collapse the wavefunction or any other process which requires randomness...

But yes, if it keeps failing for many seeds, I would play with the number of Trotter steps...

**Comment by babbush** [comment]
@idk3 can you please fix this unseeded random test?

**Comment by idk3** [comment]
Added https://github.com/ProjectQ-Framework/FermiLib/pull/147 which should address this!

**Pull request merged**
